CREATE TABLE IF NOT EXISTS master_python;
use master_python;

CREATE TABLE USERS(
    ID INT(25) AUTO_INCREMENT NOT NULL,
    NAME VARCHAR(255),
    LAST_NAME VARCHAR(255),
    EMAIL VARCHAR(255) NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    DATE DATE NOT NULL,
    CONSTRAINT PK_USUARIOS PRIMARY KEY(ID),
    CONSTRAINT UQ_EMAIL UNIQUE(EMAIL)

)ENGINE=InnoDB;

CREATE TABLE NOTES(
    ID INT(25) AUTO_INCREMENT NOT NULL,
    USER_ID INT(25) NOT NULL,
    TITLE VARCHAR(255) NOT NULL,
    DESCRIPTION MEDIUMTEXT,
    DATE DATE NOT NULL,
    CONSTRAINT PK_NOTES PRIMARY KEY(ID),
    CONSTRAINT FK_NOTES_USERS FOREIGN KEY(USER_ID) REFERENCES USERS(ID)
)ENGINE=InnoDB;